name: .NET Serve Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'  # Ajuste para a versão do .NET que você está usando

    - name: Run .NET Serve
      run: |
        cd /wwwroot  # Altere para o caminho correto
        dotnet serve
