name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main  # Substitua pelo nome da sua branch principal

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Altere conforme sua versão do .NET

    - name: Restaurar dependências
      run: dotnet restore

    - name: Compilar aplicação
      run: dotnet publish -c Release --output release

    - name: Copiar arquivos para GitHub Pages
      run: |
        mkdir -p ./deploy
        cp -r release/wwwroot/* ./deploy/

    - name: Deploy para GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: deploy
        clean: true
