name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main  # A branch que voc칡 deseja fazer o deploy, altere para a sua

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do c칩digo
      - name: 游댳 Checkout do c칩digo
        uses: actions/checkout@v4

      # Instalar .NET SDK
      - name: 游댳 Instalar .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x  # Altere para a vers칚o correta do seu projeto

      # Publicar Blazor WebAssembly
      - name: 游댳 Publicar Blazor WebAssembly
        run: |
          dotnet publish -c Release -o ./publish

      # Configurar GitHub Pages (usando a a칞칚o do GitHub Pages para publicar)
      - name: 游댳 Deploy para GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # A branch para onde o conte칰do ser치 enviado
          folder: ./publish/wwwroot  # O diret칩rio contendo os arquivos est치ticos da aplica칞칚o
``
